### ISSUE TITLE
t/crypt.t - Failed test 'Error handling'

### ISSUE THREAD

**Issue by hightowe** [chazmcgarvey/File-KDBX#1]
I am struggling to build File::KDBX on Linux Mint 19.3, which is equivalent to Ubuntu bionic 18.04.6 LTS.

Specifically, two tests fail in t/crypt.t , as follows:

~~~
t/crypt.t .............. 1/? 
    #   Failed test 'Read handle can enter an error state'
    #   at t/crypt.t line 49.
    #          got: ''
    #     expected: '1'

    #   Failed test 'Error object is available'
    #   at t/crypt.t line 51.
    #                   undef
    #     doesn't match '(?^i:fatal)'
    # Looks like you failed 2 tests of 4.

#   Failed test 'Error handling'
#   at t/crypt.t line 53.
~~~

The lines that cause the failures (49 and 51), are:

~~~
    is $read->error, 1, 'Read handle can enter an error state';
~~~
~~~
    like $File::KDBX::IO::Crypt::ERROR, qr/fatal/i,
        'Error object is available';
~~~

Looking through the code, the only idea that I have is that my version of IO::Handle or Errno may be older than the code has seen before, but my versions are 1.36 and 1.28, and both are in core perl 5.26, so I am a bit stumped. Curious if you have any ideas?

**Comment by hightowe** [comment]
I'm not sure if this is helpful, but this is the t/crypt.t output with DEBUG_STREAM=1:

~~~
t/crypt.t .............. 1/? WRITE	File::KDBX::IO::Crypt=GLOB(0x5568041c3400)
POPPED	File::KDBX::IO::Crypt=GLOB(0x5568041c3400)
FLUSH	File::KDBX::IO::Crypt=GLOB(0x5568041c3400)
FILL	File::KDBX::IO::Crypt=GLOB(0x5568041ec380)
FILL	File::KDBX::IO::Crypt=GLOB(0x5568041ec380)
POPPED	File::KDBX::IO::Crypt=GLOB(0x5568041ec380)
FILL	File::KDBX::IO::Crypt=GLOB(0x5568041ff430)

    #   Failed test 'Read handle can enter an error state'
    #   at t/crypt.t line 49.
    #          got: ''
    #     expected: '1'

    #   Failed test 'Error object is available'
    #   at t/crypt.t line 51.
    #                   undef
    #     doesn't match '(?^i:fatal)'
POPPED	File::KDBX::IO::Crypt=GLOB(0x5568041ff430)
    # Looks like you failed 2 tests of 4.

#   Failed test 'Error handling'
#   at t/crypt.t line 53.
# Looks like you failed 1 test of 3.
t/crypt.t .............. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
~~~

**Comment by hightowe** [comment]
I figured it out. It was my version of CryptX...

The **libcryptx-perl** package in Ubuntu 18.04 LTS is version 0.056-1.

I do not know what minimum version is needed by File::KDBX, but the newest from CPAN works (0.076)

**Comment by chazmcgarvey** [comment]
Looks like CryptX 0.062 is the oldest that works. I'll see if I can reasonably work around the difference, otherwise I'll have to declare the dependency minimum version.
