### ISSUE TITLE
File::KDBX writes an unusable file

### ISSUE THREAD

**Issue by hightowe** [chazmcgarvey/File-KDBX#5]
This code:

~~~
$ cat ./kdbx_new_file_bad.pl
#!/usr/bin/perl

use strict;
#use lib '/home/<username>/perl5/lib/perl5';
use File::KDBX;

my $file = $0 . '.kdbx';
my $pw = 'test';
my $kf = undef;

my $kdbx = File::KDBX->new;
my $root_grp = $kdbx->root;
my $txn = $root_grp->begin_work( entries=>1, groups=>1, history=>1 );

my $entry = $root_grp->add_entry(
      title    => 'My Bank',
      username => 'mreynolds',
      password => 's3cr3t',
  );

$root_grp->commit();

$kdbx->dump_file($file, [ $pw, $kf] );
~~~

Writes a file with a header that appears as that of a kdbx_ver = 3.1, not 4.0, which surprised me, and neither KeePassXC or File::KeePass can open it.

- KeePassXC states: Error while reading the database: SymmetricCipher::init: Invalid IV size of 16 for ChaCha20.
- File::KeePass states: encrypt: datasize not multiple of blocksize (16 bytes) at /usr/share/perl5/File/KeePass.pm line 1047.

**Comment by chazmcgarvey** [comment]
It is normal for that to dump a version 3.1 file. A new File::KDBX database will default to 3.1 for the best compatibility and will only dump to a higher version if a feature is used that requires a higher version. For example, this line will cause a V4 dump:

    $kdbx->kdf_parameters->{+KDF_PARAM_UUID} = KDF_UUID_ARGON2D;

There are ways to control this. You can explicitly set a version, e.g.:

    $kdbx->version(0x00040000);

To prevent implicit upgrades, set the `allow_upgrade` dumper attribute to false, e.g.:

    $kdbx->dump_file($file, [ $pw, $kf], allow_upgrade => 0);
    # WARNING: This risks data loss. For example if the $kdbx has public_custom_data, that won't get
    # dumped if $kdbx->version is less than 0x00040000. It's safer to keep allow_upgrade on, but it can
    # be disabled if you need that level of control.

But there's definitely a bug here. File::KDBX should not produce an invalid database file.

**Comment by hightowe** [comment]
Thanks, Charles.

In kpcli's case (at least for now), $kdbx->version(0x00040000) is what I always want as KDBX 3.1 support is still being handled by File::KeePass.

By explicitly setting that version, I can save a valid file, the "Must provide strings to lock at /home/hightowe/perl5/lib/perl5/File/KDBX/Safe.pm line 59" problem that I reported earlier notwithstanding...

**Comment by hightowe** [comment]
Oops. I spoke a little too soon. By explicitly setting $kdbx->version(0x00040000) I can write a file that File::KDBX can open, but not KeePassXC. It gives the error "Error while reading the database: SymmetricCipher::init: Invalid IV size of 16 for ChaCha20." It also does not help to add $kdbx->kdf_parameters->{+KDF_PARAM_UUID} = KDF_UUID_ARGON2D; ...

**Comment by chazmcgarvey** [comment]
Try 0.906 once it reaches a CPAN mirror near you. Reopen if you still have issues.

Yeah, `$kdbx->version(0x00040000)` is fine. File::KDBX will never automatically downgrade a database, so by doing this the version is guaranteed to be at least v4.0. With implicit upgrades on, the version could bump up to v4.1 (if you don't want that, you can disable `allow_upgrade` as I said).

Thanks for the bug reports. You're exercising some pretty typical codepaths which are buggier than they should be because I don't really have to handle newly constructed fresh databases in my own application. Hopefully there aren't too many more bugs like this.
