### ISSUE TITLE
How to properly change the KDF?

### ISSUE THREAD

**Issue by hightowe** [chazmcgarvey/File-KDBX#6]
This code:

~~~
#!/usr/bin/perl

use strict;
#use lib '/home/<username>/perl5/lib/perl5';
use File::KDBX;
use File::KDBX::Constants (qw(:all));
use File::KDBX::Util (qw(:all));
use Data::Dumper;

my $file = $0 . '.kdbx';
my $pw = 'test';
my $kf = undef;

my $kdbx = File::KDBX->new;
printf "ver-1: %s\n", $kdbx->version;
printf "kdf-1: %s\n", format_uuid($kdbx->kdf_parameters->{KDF_PARAM_UUID()},'-');

# Set the version
$kdbx->version(KDBX_VERSION_4_1());

# Set the KDF
# Commenting these lines makes a valid KDBX4 file, with AES-KDF.
# Uncommenting either of them causes KeePassXC to fail to load the file,
# with error: Unsupported key derivation function (KDF) or invalid parameters
$kdbx->kdf_parameters->{KDF_PARAM_UUID()} = KDF_UUID_ARGON2D();
#$kdbx->kdf_parameters->{KDF_PARAM_UUID()} = KDF_UUID_ARGON2ID();

printf "ver-2: %s\n", $kdbx->version;
printf "kdf-2: %s\n", format_uuid($kdbx->kdf_parameters->{KDF_PARAM_UUID()},'-');

my $root_grp = $kdbx->root;
my $txn = $root_grp->begin_work( entries=>1, groups=>1, history=>1);

my $entry = $root_grp->add_entry(
      title    => 'My Bank',
      username => 'mreynolds',
      password => 's3cr3t',
  );

$root_grp->commit();

$kdbx->dump_file($file, [ $pw, $kf] );

exit;
~~~

creates usable databases when the $kdbx->kdf_parameters->{KDF_PARAM_UUID()} values are left alone, but creates ones that KeePassXC cannot open when those values are set (to ARGON2D or ARGON2ID as shown in the code).

Note that File::KDBX can load the files in all cases, and shows that the KDF is AES in all cases...

**Comment by chazmcgarvey** [comment]
You don't want to change the KDF type without also settings its associated parameters. So, replace:

```
$kdbx->kdf_parameters->{KDF_PARAM_UUID()} = KDF_UUID_ARGON2D();
```

with:

```
$kdbx->kdf_parameters({
    KDF_PARAM_UUID() => KDF_UUID_ARGON2D(),
    KDF_PARAM_ARGON2_ITERATIONS() => KDF_DEFAULT_ARGON2_ITERATIONS,
    KDF_PARAM_ARGON2_MEMORY() => KDF_DEFAULT_ARGON2_MEMORY,
    KDF_PARAM_ARGON2_PARALLELISM() => KDF_DEFAULT_ARGON2_PARALLELISM,
    KDF_PARAM_ARGON2_VERSION() => KDF_DEFAULT_ARGON2_VERSION,
});
```

What's happening is the KDBX file being written does have the correct KDF set, but it's missing the expected parameters. The File::KDBX loader doesn't care that they're missing (it just uses default values), but KeePassXC cares.

The File::KDBX loader is intentionally lax. The dumper is too lax in cases like this - it will (often silently) dump what you say even if other KDBX implementations with non-permissive loaders won't like it.

How I think I want to handle situations like this is to issue warnings when dumping something dubious. Applications that want to be strict can catch warnings or make warnings fatal (`use warnings FATAL => 'File::KDBX';`).

- [ ] Warn when dumping dubious things (like weird KDF params).
- [ ] Document the correct way to change the KDF.
- [ ] Maybe: Add a `strict` attribute to dumper as an alternative way to make warnings fatal.
- [ ] Maybe: Make the dumper strict by default?
- [ ] Maybe: Make the database smart enough to automatically add missing required KDF parameters, to be more DWIM.

**Comment by hightowe** [comment]
Got it.

Thanks!
